# Promise 源码实现

### 核心逻辑

1.  Promise 是一个类，在执行这个类的时候，需要传递一个执行器 executor 进去，执行器会立即执行
2.  Promise 有三种状态，分别为 pending(等待)，rejected(失败)，fulfilled(成功)。初始状态为 pending。状态只能从 pending 到 fulfilled 或者从 pending 到 rejected。状态一旦发生变化，就不可再次更改。
3.  执行器 executor 接受两个函数参数 resolve 和 reject，用于改变 Promise 的状态。resolve 用于将状态改变成 fulfilled，并保存成功后的值 value，reject 用于将状态改变成 rejected，并保存失败的原因 reason。
4.  Promise 拥有一个 then 方法，该方法拥有两个参数 onFulfilled，onRejected。用于处理状态变化时，调用相对应的回调方法。当状态为 fulfilled 时，调用 onFulfilled 方法，并传入成功的的值 value 作为参数；当状态为 rejected 时，调用 onRejected 方法，并传入失败的原因 reason 作为参数。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    // executor是一个执行器，进入会立即执行，并传入resolve和reject方法
    executor(this.resolve, this.reject)
  }
  // 实例对象的一个属性，初始为等待
  status = PENDING
  // 成功之后的值
  value = undefined
  // 失败之后的原因
  reason = undefined

  // resolve和reject为什么要用箭头函数？
  // 如果直接调用的话，普通函数this指向的是window或者undefined
  // 用箭头函数就可以让this指向当前实例对象
  resolve = (value) => {
    // 判断状态是不是等待，阻止程序向下执行
    if (this.status !== PENDING) {
      return
    }
    // 将状态改成成功
    this.status = FULFILLED
    // 保存成功之后的值
    this.value = value
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    // 将状态改为失败
    this.status = REJECTED
    // 保存失败之后的原因
    this.reason = reason
  }

  then(onFulfilled, onRejected) {
    //判断状态
    if (this.status === FULFILLED) {
      // 调用成功回调，并且把值返回
      onFulfilled(this.value)
    } else if (this.status === REJECTED) {
      // 调用失败回调，并且把原因返回
      onRejected(this.reason)
    }
  }
}
```

### 异步实现

```js
const p = new MyPromise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 2000)
})
```

现在情况下，假设 executor 中，存在异步逻辑，在 then 方法执行中，由于状态还没发生变化，因此就无法处理相对应的成功会失败回调。因此，这种情况下，需执行以下几步。

1. 当 then 方法执行时，如果 Promise 的状态还为发生变化，缓存相对应的成功或失败回调。
2. 当 resove 或者 reject 执行时，判断相对应的回调是否存在，存在则执行相对应的回调函数。

```js
class MyPromise {
  constructor(executor) {
    executor(this.resolve, this.reject)
  }
  status = PENDING
  value = undefined
  reason = undefined
  // 成功回调
  onFulfilledCallback = undefined
  // 失败回调
  onRejectedCallback = undefined

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    // 判断成功回调是否存在。如果存在，则调用
    this.onFulfilledCallback && this.onFulfilledCallback(this.value)
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    // 判断失败回调是否存在。如果存在，则调用
    this.onRejectedCallback && this.onRejectedCallback(this.reason)
  }

  then(onFulfilled, onRejected) {
    if (this.status === FULFILLED) {
      onFulfilled(this.value)
    } else if (this.status === REJECTED) {
      onRejected(this.reason)
    } else {
      // 等待，将成功与失败回调进行缓存
      this.onFulfilledCallback = onFulfilled
      this.onRejectedCallback = onRejected
    }
  }
}
```

### then 方法多次调用

Promise 的 then 方法，可以被多次调用，如以下代码：

```js
const p = new MyPromise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 2000)
})

p.then(
  (val) => {
    console.log('value:' + val)
  },
  (reason) => {
    console.log('reason:' + reason)
  }
)
p.then(
  (val) => {
    console.log('value:' + val)
  },
  (reason) => {
    console.log('reason:' + reason)
  }
)
```

因此，在异步的情况下，需将对应的回调函数已数组的方式，全部缓存。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    executor(this.resolve, this.reject)
  }
  status = PENDING
  value = undefined
  reason = undefined
  // 成功回调
  onFulfilledCallback = []
  // 失败回调
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    // 判断成功回调是否存在。如果存在，则调用
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()(this.value)
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    // 判断失败回调是否存在。如果存在，则调用
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()(this.reason)
    }
  }

  then(onFulfilled, onRejected) {
    if (this.status === FULFILLED) {
      onFulfilled(this.value)
    } else if (this.status === REJECTED) {
      onRejected(this.reason)
    } else {
      // 等待，将成功与失败回调进行缓存
      this.onFulfilledCallback.push(onFulfilled)
      this.onRejectedCallback.push(onRejected)
    }
  }
}
```

### then 方法的链式调用

then 方法可以被链式调用的，后面 then 方法的回调函数拿到的值是上一个 then 方法的回调函数的返回值。

1. then 需返回一个 Promise 对象。
2. 当上一个 then 方法 返回的值 x 不为 Promise 对象时，通过 resolve(x) 将 x 传递至下一个 then 方法。
3. 当上一个 then 方法 返回的值 x 为 Promise 对象时，则需先去查看 返回的 Promise 的状态，如成功，则调用 resolve 将成功的值传递给下一个 Promise 对象。如失败，则 调用 reject 将失败的原因传递给下一个 Promise 对象。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    executor(this.resolve, this.reject)
  }
  status = PENDING
  value = undefined
  reason = undefined
  onFulfilledCallback = []
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()(this.value)
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()(this.reason)
    }
  }

  then(onFulfilled, onRejected) {
    const promise2 = new MyPromise((resolve, reject) => {
      //判断状态
      if (this.status === FULFILLED) {
        // x是上一个promise回调函数的return返回值
        // 判断 x 的值时普通值还是 promise 对象
        // 如果是普通值 直接调用 resolve
        // 如果是 promise 对象 查看 promise 对象返回的结果
        // 再根据 promise 对象返回的结果 决定调用 resolve 还是 reject
        const x = onFulfilled(this.value)
        resolvePromise(x, resolve, reject)
      } else if (this.status === REJECTED) {
        onRejected(this.reason)
      } else {
        this.onFulfilledCallback.push(onFulfilled)
        this.onRejectedCallback.push(onRejected)
      }
    })
    return promise2
  }
}

function resolvePromise(x, resolve, reject) {
  // 判断 x 是不是其实例对象
  if (x instanceof MyPromise) {
    // promise 对象
    // x.then(value => resolve(value), reason => reject(reason))
    // 简化之后
    x.then(resolve, reject)
  } else {
    // 普通值
    resolve(x)
  }
}
```

### then 方法链式调用识别 Promise 对象自返回

如以下代码：

```js
const p = new Promise((resolve) => {
  resolve('success')
})

const p1 = p.then(() => {
  return p1
}) // Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>
```

如果 then 方法返回的是自己的 promise 对象，则会发生 promise 的嵌套，这个时候程序会报错。

因此，将 then 方法 进行改造。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    executor(this.resolve, this.reject)
  }
  status = PENDING
  value = undefined
  reason = undefined
  onFulfilledCallback = []
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()(this.value)
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()(this.reason)
    }
  }

  then(onFulfilled, onRejected) {
    const promise2 = new MyPromise((resolve, reject) => {
      if (this.status === FULFILLED) {
        // 因为new Promise需要执行完成之后才有promise2，同步代码中没有pormise2，
        // 所以这部分代码需要异步执行
        setTimeout(() => {
          let x = onFulfilled(this.value)
          //需要判断then之后return的promise对象和原来的是不是一样的，
          //判断x和promise2是否相等，所以给resolvePromise中传递promise2过去
          resolvePromise(promise2, x, resolve, reject)
        }, 0)
      } else if (this.status === REJECTED) {
        onRejected(this.reason)
      } else {
        this.onFulfilledCallback.push(onFulfilled)
        this.onRejectedCallback.push(onRejected)
      }
    })
    return promise2
  }
}

function resolvePromise(promise2, x, resolve, reject) {
  // 如果相等了，说明return的是自己，抛出类型错误并返回
  if (promise2 === x) {
    return reject(
      new TypeError('Chaining cycle detected for promise #<Promise>')
    )
  }
  if (x instanceof MyPromise) {
    x.then(resolve, reject)
  } else {
    resolve(x)
  }
}
```

此时调用

```js
let promise = new MyPromise((resolve, reject) => {
  resolve('success')
})

// 这个时候将promise定义一个p1，然后返回的时候返回p1这个promise
let p1 = promise.then((value) => {
  console.log(1)
  console.log('resolve', value)
  return p1
})

// 运行的时候会走reject
p1.then(
  (value) => {
    console.log(2)
    console.log('resolve', value)
  },
  (reason) => {
    console.log(3)
    console.log(reason.message)
  }
)

// 1
// resolve success
// 3
// Chaining cycle detected for promise #<Promise>
```

### 捕获错误及 then 链式调用其他状态代码补充

1. 执行器 executor 执行报错，在 Promise 类构造器中，添加 try catch，报错时，调用 reject。
2. then 方法，回调函数中报错，在下一个 then 方法中，错误回调中体现。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    // 执行器 执行报错
    try {
      executor(this.resolve, this.reject)
    } catch (e) {
      this.reject(e)
    }
  }
  status = PENDING
  value = undefined
  reason = undefined
  onFulfilledCallback = []
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()(this.value)
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()(this.reason)
    }
  }

  then(onFulfilled, onRejected) {
    const promise2 = new MyPromise((resolve, reject) => {
      if (this.status === FULFILLED) {
        setTimeout(() => {
          // then 回调中报错
          try {
            const x = onFulfilled(this.value)
            resolvePromise(promise2, x, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else if (this.status === REJECTED) {
        onRejected(this.reason)
      } else {
        this.onFulfilledCallback.push(onFulfilled)
        this.onRejectedCallback.push(onRejected)
      }
    })
    return promise2
  }
}

function resolvePromise(promise2, x, resolve, reject) {
  if (promise2 === x) {
    return reject(
      new TypeError('Chaining cycle detected for promise #<Promise>')
    )
  }
  if (x instanceof MyPromise) {
    x.then(resolve, reject)
  } else {
    resolve(x)
  }
}
```

接下来对 失败回调 及 异步情况 进行补充。

1. 失败回调与成功回调处理类似。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    try {
      executor(this.resolve, this.reject)
    } catch (e) {
      this.reject(e)
    }
  }
  status = PENDING
  value = undefined
  reason = undefined
  onFulfilledCallback = []
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()()
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()()
    }
  }

  then(onFulfilled, onRejected) {
    const promise2 = new MyPromise((resolve, reject) => {
      if (this.status === FULFILLED) {
        setTimeout(() => {
          try {
            const x = onFulfilled(this.value)
            resolvePromise(promise2, x, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else if (this.status === REJECTED) {
        // 调用失败回调，并且把原因返回
        setTimeout(() => {
          // x是上一个promise回调函数的return返回值
          // 判断 x 的值时普通值还是 promise 对象
          // 如果是普通值 直接调用 resolve
          // 如果是 promise 对象 查看 promise 对象返回的结果
          // 再根据 promise 对象返回的结果 决定调用 resolve 还是 reject
          try {
            const x = onRejected(this.reason)
            resolvePromise(promise2, x, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else {
        // 异步处理
        this.onFulfilledCallback.push(() => {
          setTimeout(() => {
            try {
              const x = onFulfilled(this.value)
              resolvePromise(promise2, x, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
        this.onRejectedCallback.push(() => {
          setTimeout(() => {
            try {
              const x = onRejected(this.reason)
              resolvePromise(promise2, x, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
      }
    })
    return promise2
  }
}

function resolvePromise(promise2, x, resolve, reject) {
  if (promise2 === x) {
    return reject(
      new TypeError('Chaining cycle detected for promise #<Promise>')
    )
  }
  if (x instanceof MyPromise) {
    x.then(resolve, reject)
  } else {
    resolve(x)
  }
}
```

### 将 then 方法的参数变成可选参数

then 方法的两个参数都是可选参数，我们可以不传参数。下面的参数可以传递到最后进行返回。

``` 
var promise = new Promise((resolve, reject) => {
      resolve(100)
    })
    promise
      .then()
      .then()
      .then()
      .then(value => console.log(value))
// 在控制台最后一个then中输出了100

// 这个相当于
promise
  .then(value => value)
  .then(value => value)
  .then(value => value)
  .then(value => console.log(value))
```

所以，需对 then 方法 进行修改。

```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    try {
      executor(this.resolve, this.reject)
    } catch (e) {
      this.reject(e)
    }
  }
  status = PENDING
  value = undefined
  reason = undefined
  onFulfilledCallback = []
  onRejectedCallback = []

  resolve = (value) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = FULFILLED
    this.value = value
    while (this.onFulfilledCallback.length) {
      this.onFulfilledCallback.shift()()
    }
  }

  reject = (reason) => {
    if (this.status !== PENDING) {
      return
    }
    this.status = REJECTED
    this.reason = reason
    while (this.onRejectedCallback.length) {
      this.onRejectedCallback.shift()()
    }
  }

  then(onFulfilled, onRejected) {
    const promise2 = new MyPromise((resolve, reject) => {
      // then 的可选参数
      onFulfilled = onFulfilled ? onFulfilled : (value) => value
      onRejected = onRejected
        ? onRejected
        : (reason) => {
            throw reason
          }
      if (this.status === FULFILLED) {
        setTimeout(() => {
          try {
            const x = onFulfilled(this.value)
            resolvePromise(promise2, x, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else if (this.status === REJECTED) {
        setTimeout(() => {
          try {
            const x = onRejected(this.reason)
            resolvePromise(promise2, x, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else {
        this.onFulfilledCallback.push(() => {
          setTimeout(() => {
            try {
              const x = onFulfilled(this.value)
              resolvePromise(promise2, x, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
        this.onRejectedCallback.push(() => {
          setTimeout(() => {
            try {
              const x = onRejected(this.reason)
              resolvePromise(promise2, x, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
      }
    })
    return promise2
  }
}

function resolvePromise(promise2, x, resolve, reject) {
  if (promise2 === x) {
    return reject(
      new TypeError('Chaining cycle detected for promise #<Promise>')
    )
  }
  if (x instanceof MyPromise) {
    x.then(resolve, reject)
  } else {
    resolve(x)
  }
}
```

### Promise.all 方法实现

- all 方法接收一个数组，数组中可以是普通值也可以是 promise 对象
- 数组中值得顺序一定是我们得到的结果的顺序
- promise 返回值也是一个 promise 对象，可以调用 then 方法
- 如果数组中所有值是成功的，那么 then 里面就是成功回调，如果有一个值是失败的，那么 then 里面就是失败的
- 使用 all 方法是用类直接调用，那么 all 一定是一个静态方法

```js
	static all(array) {
    const result = []
    const index = 0
    return MyPromise((resolve, reject) => {
      const addData = (i, value) => {
        result[i] = value
        index++
        // 如果计数器和数组长度相同，那说明所有的元素都执行完毕了，就可以输出了
        if (index === array.length) {
          resolve(result)
        }
      }

      for (let i = 0; i < array.length; i++) {
        const curry = array[i]
        if (curry instanceof MyPromise) {
          // promise对象就执行then，如果是resolve就把值添加到数组中去，如果是错误就执行reject返回
          curry.then(
            (value) => addData(i, value),
            (reason) => reject(reason)
          )
        } else {
          // 普通值就加到对应的数组中去
          addData(i, curry)
        }
      }
    })
  }
```

### Promise.race 方法实现

返回一个 promise，一旦迭代器中的某个 promise 解决或拒绝，返回的 promise 就会解决或拒绝。

```js
static race(array) {
    return new MyPromise((resolve, reject) => {
      for (let i = 0; i < array.length; i++) {
        const curry = array[i]
        if (curry instanceof MyPromise) {
          // 返回第一个成功的值，或失败的原因
          curry.then(resolve, reject)
        } else {
          // 返回成功
          resolve(curry)
        }
      }
    })
  }
```

### Promise.resolve 方法实现

- 如果参数就是一个 promise 对象，直接返回，如果是一个值，那么需要生成一个 promise 对象，把值进行返回
- 是 Promise 类的一个静态方法

```js
	static resolve(value) {
    // 如果是promise对象，就直接返回
    if (value instanceof MyPromise) {
      return value
    } else {
      // 如果是值就返回一个promise对象，并返回值
      return new MyPromise((resolve) => resolve(value))
    }
  }
```

### Promise.reject 方法实现

- 如果参数就是一个 promise 对象，直接返回，如果是一个值，那么需要生成一个 promise 对象，把值进行返回
- 是 Promise 类的一个静态方法

```js
	static reject(value) {
    if (value instanceof MyPromise) {
      return value
    } else {
      return new MyPromise((resolve, reject) => reject(value))
    }
  }
```

### Promise.catch 方法实现

- catch 方法是为了捕获 promise 对象的所有错误回调的
- 直接调用 then 方法，然后成功的地方传递 undefined，错误的地方传递 reason
- catch 方法是作用在原型对象上的方法

```js
	catch(onRejected) {
    return this.then(undefined, onRejected)
  }
```

### Promise.finally 方法实现

- 无论当前最终状态是成功还是失败，finally 都会执行
- 我们可以在 finally 方法之后调用 then 方法拿到结果
- 这个函数是在原型对象上用的

```js
	finally(callback) {
    // 如何拿到当前的promise的状态，使用then方法，而且不管怎样都返回callback
    // 而且then方法就是返回一个promise对象，那么我们直接返回then方法调用之后的结果即可
    // 我们需要在回调之后拿到成功的回调，所以需要把value也return
    // 失败的回调也抛出原因
    // 如果callback是一个异步的promise对象，我们还需要等待其执行完毕，所以需要用到静态方法resolve
    return this.then(
      (value) => {
        // 把callback调用之后返回的promise传递过去，并且执行promise，且在成功之后返回value
        return MyPromise.resolve(callback()).then(() => value)
      },
      (reason) => {
        // 失败之后调用的then方法，然后把失败的原因返回出去。
        return MyPromise.resolve(callback()).then(() => {
          throw reason
        })
      }
    )
  }
```
